### ISSUE TITLE
Tried running the tailwind init command and getting this error. 

### ISSUE THREAD

**Issue by PatrickWhitehouse** [tailwindcss/discuss#113]
`./node_modules/.bin/tailwind init
/Users/Patrick/Desktop/portfolio-2018/node_modules/tailwindcss/lib/cli.js:58
_commander2.default.command('init [filename]').usage('[options] [filename]').action((filename = 'tailwind.js') => {
                                                                                              ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3`

**Comment by adamwathan** [comment]
Need to update to a newer version of Node; we transpile for Node 6.0 and up.

**Comment by robmerki** [comment]
I had this problem as well, running the Bash on Windows ("Bash on Ubuntu on Windows") feature.

Fixed it by installing [n](https://github.com/tj/n):
`npm install n`
`n latest`

**Comment by Keweb** [comment]
> 
> 
> I had this problem as well, running the Bash on Windows ("Bash on Ubuntu on Windows") feature.
> 
> Fixed it by installing [n](https://github.com/tj/n):
> `npm install n`
> `n latest`

icant installing :( im using windows

**Comment by Keweb** [comment]
#SOLVED

tksh for sharing, im problem now already solved, im using git for install "./node_modules/.bin/tailwind init"
