### ISSUE TITLE
TypeError: Cannot read property 'config' of undefined

### ISSUE THREAD

**Issue by LoganDark** [tailwindcss/discuss#163]
```
0 LoganDark ~ mkdir tailwindtest
0 LoganDark ~ cd tailwindtest
0 LoganDark ~/tailwindtest npm init
... (hitting enter through the whole process)
0 LoganDark ~/tailwindtest npm i --save tailwindcss
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN tailwindtest@1.0.0 No description
npm WARN tailwindtest@1.0.0 No repository field.

+ tailwindcss@0.6.4
added 61 packages from 61 contributors and audited 120 packages in 2.552s
found 0 vulnerabilities

0 LoganDark ~/tailwindtest ./node_modules/.bin/tailwind init
Generated Tailwind config: /Users/LoganDark/tailwindtest/tailwind.js
0 LoganDark ~/tailwindtest ./node_modules/.bin/tailwind build
/Users/LoganDark/tailwindtest/node_modules/tailwindcss/lib/cli.js:85
  buildTailwind(inputFile, options.config, writeStrategy(options)).then(() => {
                                   ^

TypeError: Cannot read property 'config' of undefined
    at Command._commander2.default.command.usage.option.option.action (/Users/LoganDark/tailwindtest/node_modules/tailwindcss/lib/cli.js:85:36)
    at Command.listener (/Users/LoganDark/tailwindtest/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:182:13)
    at Command.parseArgs (/Users/LoganDark/tailwindtest/node_modules/commander/index.js:651:12)
    at Command.parse (/Users/LoganDark/tailwindtest/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/Users/LoganDark/tailwindtest/node_modules/tailwindcss/lib/cli.js:96:21)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
1 LoganDark ~/tailwindtest node -v
v10.1.0
0 LoganDark ~/tailwindtest npm -v
6.3.0
0 LoganDark ~/tailwindtest neofetch --image none
                -/+:.          LoganDark@base.local
               :++++.          --------------------
              /+++/.           Model: MacBookPro11,5
      .:-::- .+/:-``.::-       OS: Mac OS X 10.14 18A353d x86_64
   .:/++++++/::::/++++++/:`    Kernel: 18.0.0
 .:///////////////////////:`   Uptime: up 4 hours, 45 minutes
 ////////////////////////`     Packages: 355
-+++++++++++++++++++++++`      Shell: /bin/bash
/++++++++++++++++++++++/       Resolution: 1440x900
/sssssssssssssssssssssss.      DE: Aqua
:ssssssssssssssssssssssss-     WM: Quartz Compositor
 osssssssssssssssssssssssso/`  WM Theme: Blue
 `syyyyyyyyyyyyyyyyyyyyyyyy+`  Terminal: iTerm2
  `ossssssssssssssssssssss/    CPU: Intel Core i7-4870HQ (8) @ 2.50GHz
    :ooooooooooooooooooo+.     GPU: AMD Radeon R9 M370X, Intel Iris Pro
     `:+oo+/:-..-:/+o+/-       Memory: 3219MB / 16384MB

                               % s% s% s% s% s% s% s% s
```

**Comment by LoganDark** [comment]
Nevermind. Apparently, reading the docs is necessary because the CLI tool is a confusing nightmare...

**Comment by adamwathan** [comment]
I don't think saying "the CLI tool is a confusing nightmare" is totally fair, the options are documented right inline:

![image](https://user-images.githubusercontent.com/4323180/44063509-bb827e72-9f2e-11e8-92ce-58130cfddfd2.png)

But we could update the CLI tool to automatically look for a `tailwind.js` file if no config is specified, or throw a better error at least.

**Comment by LoganDark** [comment]
It's not the options. It's the usage.

How am I supposed to know I'm supposed to take a CSS file and add `@tailwind` stuff to it, then pass it to the CLI? The only thing I know is that it takes a file and some options.

Of course, I read the documentation, and it _is_ in there, but for anyone who doesn't usually read the "Getting Started" guide, the CLI really can be very counter-intuitive.

**Comment by adamwathan** [comment]
The CLI isn't the main product of the framework, it's mostly just used to initialize your config file. 99% of people are using Tailwind as a PostCSS plugin in their existing Webpack/Gulp/Parcel whatever build systems. Not sure how to communicate that information other than through documentation.

Tailwind is not a CLI tool, it's a PostCSS plugin.

**Comment by LoganDark** [comment]
Whatever. This isn't even necessary, I got past the issue.
