### ISSUE TITLE
1.0.0.beta.4, plugins, ReferenceError: colors is not defined

### ISSUE THREAD

**Issue by jean-francois-labbe** [tailwindcss/discuss#240]
I'm trying to upgrade my website to tailwindcss 1.0.0.beta.4 but I'm facing an error with this plugin configuration: https://github.com/chrisrowe/tailwindcss-triangle-after

```js
module.exports = {
  theme: {},
  variants: {},
  plugins: [
    require('tailwindcss-triangle-after/index')({
      triangles: {
        next: {
          color: colors['teal'],
          direction: 'right',
          right: '-17px',
          size: 16
        }
      },
    }),
  ],
}
```

The error is:
```
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
ReferenceError: colors is not defined
    at Object.<anonymous> (app/javascript/css/tailwind.config.js:39:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at node_modules/tailwindcss/lib/index.js:54:83
    at node_modules/tailwindcss/lib/processTailwindFeatures.js:32:20
    at runLoaders (node_modules/webpack/lib/NormalModule.js:301:20)
    at node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Promise.resolve.then.then.catch (node_modules/postcss-loader/src/index.js:208:9)````
```

It was working fine with 0.7.4.

my postcss.config.js
```javascript
var tailwindcss = require('tailwindcss');

module.exports = {
  plugins: [
    require('postcss-import'),
    tailwindcss('app/javascript/css/tailwind.config.js'),
    require('autoprefixer'),
    require('postcss-flexbugs-fixes'),
    require('postcss-preset-env')({
      autoprefixer: {
        flexbox: 'no-2009'
      },
      stage: 3
    })
  ]
}
```

How do we access to colors configuration in this new version?

**Comment by adamwathan** [comment]
The error is correct, you have no variable named colors (it’s all just
JavaScript after all).

On my phone so can’t give you a proper code example but until the plugin is
updated to work the 1.0 way where it pulls it’s config from “theme”, your
best bet is to create a variable called colors and reference that in the
other places in your config that need it.

**Comment by jean-francois-labbe** [comment]
What I don't understand is that `colors['teal']` is used in the **1.0.0-beta.4** doc here: https://next.tailwindcss.com/docs/plugins#exposing-options

```js
module.exports = {
  // ...
  plugins: [
    require('./path/to/plugin')({
      gradients: {
        'blue-green': [colors['blue'], colors['green']],
        'purple-blue': [colors['purple'], colors['blue']],
        // ...
      },
      variants: ['responsive', 'hover'],
    })
  ],
  // ...
}
```

**Comment by adamwathan** [comment]
The docs aren’t finished, lots of pages are currently incorrect and still
based on v0.x, that’s why I haven’t released the final version of v1 yet.
