### ISSUE TITLE
tailwind doesn't with npm run build

### ISSUE THREAD

**Issue by TedMarch** [tailwindcss/discuss#281]
Hi, 

When I try to  launch : npm run build, it does't work. Could you help me ?

```
OnePage@1.0.0 build /Users/ted/Documents/Dweb/HTML : CSS/Projets/OnePage
> npm tailwind build src/css/tailwind.css -o dist/css/tailwind.css


Usage: npm <command>

where <command> is one of:
    access, adduser, audit, bin, bugs, c, cache, ci, cit,
    clean-install, clean-install-test, completion, config,
    create, ddp, dedupe, deprecate, dist-tag, docs, doctor,
    edit, explore, get, help, help-search, hook, i, init,
    install, install-ci-test, install-test, it, link, list, ln,
    login, logout, ls, org, outdated, owner, pack, ping, prefix,
    profile, prune, publish, rb, rebuild, repo, restart, root,
    run, run-script, s, se, search, set, shrinkwrap, star,
    stars, start, stop, t, team, test, token, tst, un,
    uninstall, unpublish, unstar, up, update, v, version, view,
    whoami

npm <command> -h  quick help on <command>
npm -l            display full usage info
npm help <term>   search for help on <term>
npm help npm      involved overview

Specify configs in the ini-formatted file:
    /Users/ted/.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@6.9.0 /usr/local/lib/node_modules/npm

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! OnePage@1.0.0 build: `npm tailwind build src/css/tailwind.css -o dist/css/tailwind.css`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the OnePage@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```
It's my package.json
[{
  "name": "OnePage",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "build": "npm tailwind build src/css/tailwind.css -o dist/css/tailwind.css"
  },
  "devDependencies": {
    "eslint": "^5.16.0",
    "purgecss": "^1.3.0",
    "tailwindcss": "^1.0.4"
  }
}](url)

**Comment by adamwathan** [comment]
You don't need `npm` in the actual build script, change it to this and it _should_ work unless I'm missing something! 👍🏻

```js
"scripts": {
  "build": "tailwind build src/css/tailwind.css -o dist/css/tailwind.css"
},
```

**Comment by TedMarch** [comment]
It doesn't work. It's still same error messages on my Terminal

**Comment by adamwathan** [comment]
Can you create a GitHub repo that reproduces the issue? Will be easier to troubleshoot if I can pull it down.

**Comment by adamwathan** [comment]
To be clear you should be running `npm run build` on the command line, and your scripts should look like this:

```js
"scripts": {
  "build": "tailwind build src/css/tailwind.css -o dist/css/tailwind.css"
},
```

**Comment by TedMarch** [comment]
I'm new on GitHub, How can I create a GitHib repo ?

**Comment by adamwathan** [comment]
Here the instructions I found by doing a quick Google search for "how to create a github repo":

https://help.github.com/en/articles/create-a-repo

**Comment by TedMarch** [comment]
otherwise, There is something strange with my package.json. When I write something in my computer ask me a password to save this json file. 

I'm the only user of my computor and I'm in adminstrator accompt. This could be a clue ?

**Comment by adamwathan** [comment]
What operating system? If it's Windows I don't really have any experience there but if it's macOS maybe the permissions are incorrect on the files in the project.

Either way I think the biggest piece of the problem is that `npm tailwind` is an invalid command, so the script needs to change to just `tailwind ...`.

Can you paste the entire terminal output that you see when running `npm run build` and paste your updated package.json?

**Comment by TedMarch** [comment]
Mac OS MOJAVE. 


```
> OnePage@1.0.0 build /Users/ted/Documents/Dweb/HTML : CSS/Projets/OnePage
> tailwind build src/css/tailwind.css -o dist/css/tailwind.css

sh: tailwind: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! OnePage@1.0.0 build: `tailwind build src/css/tailwind.css -o dist/css/tailwind.css`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the OnePage@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ted/.npm/_logs/2019-06-15T17_09_17_970Z-debug.log

```

**Comment by TedMarch** [comment]
It's the entire paste when I run : npm run build

**Comment by TedMarch** [comment]
Do you need the debug.log ?

**Comment by TedMarch** [comment]
This is my debug log: 

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@6.9.0
3 info using node@v12.4.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle OnePage@1.0.0~prebuild: OnePage@1.0.0
6 info lifecycle OnePage@1.0.0~build: OnePage@1.0.0
7 verbose lifecycle OnePage@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle OnePage@1.0.0~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/ted/Documents/Dweb/HTML : CSS/Projets/OnePage/node_modules/.bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle OnePage@1.0.0~build: CWD: /Users/ted/Documents/Dweb/HTML : CSS/Projets/OnePage
10 silly lifecycle OnePage@1.0.0~build: Args: [
10 silly lifecycle   '-c',
10 silly lifecycle   'tailwind build src/css/tailwind.css -o dist/css/tailwind.css'
10 silly lifecycle ]
11 info lifecycle OnePage@1.0.0~build: Failed to exec build script
12 verbose stack Error: OnePage@1.0.0 build: `tailwind build src/css/tailwind.css -o dist/css/tailwind.css`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at ChildProcess.emit (events.js:200:13)
12 verbose stack     at maybeClose (internal/child_process.js:1021:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
13 verbose pkgid OnePage@1.0.0
14 verbose cwd /Users/ted/Documents/Dweb/HTML : CSS/Projets/OnePage
15 verbose Darwin 18.6.0
16 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
17 verbose node v12.4.0
18 verbose npm  v6.9.0
19 error file sh
20 error code ELIFECYCLE
21 error errno ENOENT
22 error syscall spawn
23 error OnePage@1.0.0 build: `tailwind build src/css/tailwind.css -o dist/css/tailwind.css`
23 error spawn ENOENT
24 error Failed at the OnePage@1.0.0 build script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

**Comment by TedMarch** [comment]
I restored my OS system. Now, it works parfaitly. 
Thanks Adam for your Help.
